### ISSUE TITLE
Jenkins unavailable

### ISSUE THREAD

**Issue by keithpitty** [Homebrew/homebrew-devel-only#21]
The latest build for https://github.com/Homebrew/homebrew-devel-only/pull/20 is unavailable. When I click on the link (http://bot.brew.sh/job/Homebrew%20Devel-Only%20Pull%20Requests/56/) it times out. Is there something awry with the Jenkins build infrastructure for Homebrew?

**Comment by keithpitty** [comment]
Was caused by a hardware issue.

**Comment by DomT4** [comment]
Yeah, sorry, we lost our CI for the day. It's backtracking through the day's PRs in various taps now.
